# nifty_engine/config.py

import os

# Angel One API configuration
ANGEL_ONE_API_KEY = os.getenv("ANGEL_ONE_API_KEY", "YOUR_ANGEL_ONE_API_KEY")
ANGEL_ONE_CLIENT_CODE = os.getenv("ANGEL_ONE_CLIENT_CODE", "YOUR_CLIENT_CODE")
ANGEL_ONE_PASSWORD = os.getenv("ANGEL_ONE_PASSWORD", "YOUR_PASSWORD")
ANGEL_ONE_TOTP_SECRET = os.getenv("ANGEL_ONE_TOTP_SECRET", "YOUR_TOTP_SECRET")

# Telegram Configuration
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "YOUR_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "YOUR_CHAT_ID")

# Database Configuration
DB_NAME = "nifty_data.db"

# Trading Settings
NIFTY_SYMBOL = "NIFTY"
BANKNIFTY_SYMBOL = "BANKNIFTY"
DEFAULT_TIMEFRAME = "1m"
