# config.py

# Angel One API configuration
ANGEL_ONE_API_KEY = "YOUR_ANGEL_ONE_API_KEY"
ANGEL_ONE_SECRET_KEY = "YOUR_ANGEL_ONE_SECRET_KEY"
ANGEL_ONE_USERNAME = "YOUR_ANGEL_ONE_USERNAME"
ANGEL_ONE_PASSWORD = "YOUR_ANGEL_ONE_PASSWORD"
ANGEL_ONE_TOTP_SECRET = "YOUR_ANGEL_ONE_TOTP_SECRET"

# Dhan API configuration
DHAN_CLIENT_ID = "YOUR_DHAN_CLIENT_ID"
DHAN_ACCESS_TOKEN = "YOUR_DHAN_ACCESS_TOKEN"
